version: '3.4'

services:
  identityserver:
    image: identityserver
    container_name: identityserver
    build:
      context: ./IdentityServer/
      dockerfile: Dockerfile
    ports:
      - "8001:8001"

  react:
    image: react
    container_name: react
    build:
      context: ./React/
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "5001:5001"
    # volumes:
    #   - C:\Users\Administrator\.aspnet\https:/usr/app
    environment:
      # - ASPNETCORE_ENVIRONMENT=Development
      # - SSL_CRT_FILE=/usr/app/reactaspnetcore.client.pem
      # - SSL_KEY_FILE=/usr/app/reactaspnetcore.client.key
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/usr/app/reactaspnetcore.client.pfx
      - ASPNETCORE_URLS=https://+:8001
      - ASPNETCORE_HTTPS_PORT=8001
      - PORT=5001
      - HTTPS=true
      - BROWSER=none
      - REACT_APP_AUTH_SERVER_URL=https://localhost:5001
      - REACT_APP_CLIENT_URL=http://localhost:5001
      - REACT_APP_CLIENT_ID=react.client